### ISSUE TITLE
osu!mania accuracy is being counted wrongly

### ISSUE THREAD

**Issue by Dopaminos** [AlphaOSU/AlphaOSU#14]
alphaosu predicts me 95%
![image](https://github.com/AlphaOSU/AlphaOSU/assets/42616718/fbd11fbe-9e78-4ffd-b2af-c0b19a1594f6)

when my current score is... yea..
![image](https://github.com/AlphaOSU/AlphaOSU/assets/42616718/c8e75c7f-1bf1-46a3-aa4c-03f29d62f0a5)

**Comment by smdbs01** [comment]
There was an [update on Mania's pp accuracy](https://osu.ppy.sh/home/news/2022-10-09-changes-to-osu-mania-sr-and-pp) back in 2022. 
Basically the accuracy displayed in game is calculated using max=300, while the actual accuracy that is used to calculate PP uses max=320.
