### ISSUE TITLE
Collect more players' BP to improve the accuracy of recommendations for the lower-level players

### ISSUE THREAD

**Issue by xz1z1z1z1z** [AlphaOSU/AlphaOSU#3]

**Comment by xz1z1z1z1z** [comment]
@Keytoyze 
I want to know how many players we can get from the global leaderboard and country leaderboards?

**Comment by Keytoyze** [comment]
Due to the limit of the osu! website, 10,000 players for the global leaderboard and 10,000 players for the CN country leaderboard are collected currently,

**Comment by xz1z1z1z1z** [comment]
How about grabing data directly using the beatmapid and player id but not the best performance of the top players?

**Comment by Keytoyze** [comment]
> How about grabing data directly using the beatmapid and player id but not the best performance of the top players?

It's inefficient since we can obtain only one score in a single request, and due to the ppy's limit we should not request faster than 1 req/sec.
