### ISSUE TITLE
Support synchronizing data immediately and online training

### ISSUE THREAD

**Issue by Keytoyze** [AlphaOSU/AlphaOSU#5]
Current framework only serves the users whose rank < 10,000, and requires 3 days to update the score data and retrain the model. By immediately synchronizing, we hope that it can serve all users, and make recommendations more timely.

Frontend: @Rain7-osu 
Backend: @Keytoyze 
Algorithm: @Caicinov

**Comment by Rain7-osu** [comment]
front-end has supported.

**Comment by Keytoyze** [comment]
Finish
